apiVersion: v1
kind: Service
metadata:
    name: nodejs
spec:
    type: LoadBalancer
    selector:
        app: nodejs
    ports:
        - name: saas
          port: 8080
          targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: nodejs
spec:
    selector:
        matchLabels:
            app: nodejs
    template:
        metadata:
            labels:
                app: nodejs
        spec:
            containers:
                - name: nodejs
                  image: leezzxuan/nodejs:latest
                  tty: true
                  volumeMounts:
                      - name: saas
                        mountPath: /root/project
            volumes:
                - name: saas
                  hostPath:
                      path: /Users/fstre/Documents/project
