apiVersion: v1
kind: Service
metadata:
    name: php-service
spec:
    selector:
        app: php
    ports:
        - name: php
          port: 9000
          targetPort: 9000
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: php-deployment
spec:
    selector:
        matchLabels:
            app: php
    template:
        metadata:
            labels:
                app: php
        spec:
            containers:
                - name: php
                  image: php:7.1-fpm
                  volumeMounts:
                      - name: web-root
                        mountPath: /usr/share/nginx/html
            volumes:
                - name: web-root
                  hostPath:
                      path: /Users/fstre/Documents/project
